[lib]
proc-macro = true

[package]
name = "html-temple-macros"
version = "0.0.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
html-temple-parser = { path = "../parser" }